

import Head from 'next/head'




export default function Home() {
  return (
    <>
      <Head>
        <title> Front End Developer </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/programmer_119550.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700;900&display=swap" rel="stylesheet"/>
      </Head>
      <div>
        <h1>Front End Developer</h1>
      </div>     
    </>
  )
}
